export interface CharacterOption {
	id: number;
	name: string;
	group: string;
	speed?: number;
	url?: string;
	useweapon: string;
}

export const characterOptions: readonly CharacterOption[] = [
	{id: 1 ,name: "カラス対魔獣スタンダード" , group: "カラス" ,speed:999 ,useweapon: "杖"},
	{id: 2 ,name: "カラス仮想戦ライトフォーム" , group: "カラス" ,speed:999 ,useweapon: "杖"},
	{id: 3 ,name: "カラス殲滅型ウィッチ" , group: "カラス" ,speed:999 ,useweapon: "杖"},
	{id: 4 ,name: "カラス浄化型カンナギ" , group: "カラス" ,speed:999 ,useweapon: "杖"},
	{id: 5 ,name: "カラス暴虐型インフェルノ" , group: "カラス" ,speed:999 ,useweapon: "杖"},
	{id: 6 ,name: "カラス調律型スチームアームズ" , group: "カラス" ,speed:999 ,useweapon: "杖"},
	{id: 7 ,name: "カラス浄化型プリエステス" , group: "カラス" , speed:999 ,useweapon: "杖"},
	{id: 8 ,name: "カラス真夏型スウィムドレス" , group: "カラス" , speed:999 ,useweapon: "杖"},
	{id: 9 ,name: "カラス花鳥・対魔獣スタンダード" , group: "カラス" , speed:999 ,useweapon: "杖"},
	{id: 10 ,name: "カラス童話型イヴルウルフ" , group: "カラス" , speed:999 ,useweapon: "杖"},
	{id: 11 ,name: "カラス祭儀型セントホリデー" , group: "カラス" , speed:999 ,useweapon: "杖"},
	{id: 12 ,name: "カラス花鳥・浄化型プリエステス" , group: "カラス" , speed:999 ,useweapon: "杖"},
	{id: 13 ,name: "ハクチョウ対魔獣スタンダード" , group: "ハクチョウ" , speed:999 ,useweapon: "剣"},
	{id: 14 ,name: "ハクチョウ仮想戦ライトフォーム" , group: "ハクチョウ" , speed:999 ,useweapon: "杖"},
	{id: 15 ,name: "ハクチョウ殲滅型ウィッチ" , group: "ハクチョウ" , speed:999 ,useweapon: "杖"},
	{id: 16 ,name: "ハクチョウ浄化型カンナギ" , group: "ハクチョウ" , speed:999 ,useweapon: "杖"},
	{id: 17 ,name: "ハクチョウ暴虐型アビス" , group: "ハクチョウ" , speed:999 ,useweapon: "杖"},
	{id: 18 ,name: "ハクチョウ調律型スチームアームズ" , group: "ハクチョウ" , speed:999 ,useweapon: "杖"},
	{id: 19 ,name: "ハクチョウ浄化型プリエステス" , group: "ハクチョウ" , speed:999 ,useweapon: "杖"},
	{id: 20 ,name: "ハクチョウ真夏型スウィムドレス" , group: "ハクチョウ" , speed:999 ,useweapon: "杖"},
	{id: 21 ,name: "ハクチョウ花鳥・対魔獣スタンダード" , group: "ハクチョウ" , speed:999 ,useweapon: "杖"},
	{id: 22 ,name: "ハクチョウ童話型イヴルスネイク" , group: "ハクチョウ" , speed:999 ,useweapon: "杖"},
	{id: 23 ,name: "ハクチョウ祭儀型セントホリデー" , group: "ハクチョウ" , speed:999 ,useweapon: "杖"},
	{id: 24 ,name: "ハクチョウ花鳥・浄化型プリエステス" , group: "ハクチョウ" , speed:999 ,useweapon: "杖"},
	{id: 25 ,name: "スズメ対魔獣スタンダード" , group: "スズメ" , speed:999 ,useweapon: "杖"},
	{id: 26 ,name: "スズメ仮想戦ライトフォーム" , group: "スズメ" , speed:999 ,useweapon: "杖"},
	{id: 27 ,name: "スズメ殲滅型ウィッチ" , group: "スズメ" , speed:999 ,useweapon: "杖"},
	{id: 28 ,name: "スズメ浄化型カンナギ" , group: "スズメ" , speed:999 ,useweapon: "杖"},
	{id: 29 ,name: "スズメ対魔女ダストストーム" , group: "スズメ" , speed:999 ,useweapon: "杖"},
	{id: 30 ,name: "スズメ天文型スターラヴァーズ" , group: "スズメ" , speed:999 ,useweapon: "杖"},
	{id: 31 ,name: "スズメ祭儀型トリックナイト" , group: "スズメ" , speed:999 ,useweapon: "杖"},
	{id: 32 ,name: "スズメ暴虐型ディザスター" , group: "スズメ" , speed:999 ,useweapon: "杖"},
	{id: 33 ,name: "スズメ風月・対魔獣スタンダード" , group: "スズメ" , speed:999 ,useweapon: "杖"},
	{id: 34 ,name: "スズメ祭儀型ショコラモード" , group: "スズメ" , speed:999 ,useweapon: "杖"},
	{id: 35 ,name: "エナガ対魔獣スタンダード" , group: "エナガ" , speed:999 ,useweapon: "杖"},
	{id: 36 ,name: "エナガ仮想戦ライトフォーム" , group: "エナガ" , speed:999 ,useweapon: "杖"},
	{id: 37 ,name: "エナガ殲滅型ウィッチ" , group: "エナガ" , speed:999 ,useweapon: "杖"},
	{id: 38 ,name: "エナガ浄化型カンナギ" , group: "エナガ" , speed:999 ,useweapon: "杖"},
	{id: 39 ,name: "エナガ対魔女ダストストーム" , group: "エナガ" , speed:999 ,useweapon: "杖"},
	{id: 40 ,name: "エナガ天文型スターラヴァーズ" , group: "エナガ" , speed:999 ,useweapon: "杖"},
	{id: 41 ,name: "エナガ暴虐型ジャッジメント" , group: "エナガ" , speed:999 ,useweapon: "杖"},
	{id: 42 ,name: "エナガ祭儀型トリックナイト" , group: "エナガ" , speed:999 ,useweapon: "杖"},
	{id: 43 ,name: "エナガ花鳥・対魔獣スタンダード" , group: "エナガ" , speed:999 ,useweapon: "杖"},
	{id: 44 ,name: "エナガ祭儀型ショコラモード" , group: "エナガ" , speed:999 ,useweapon: "杖"},
	{id: 45 ,name: "フクロウ対魔獣スタンダード" , group: "フクロウ" , speed:999 ,useweapon: "杖"},
	{id: 46 ,name: "フクロウ仮想戦ライトフォーム" , group: "フクロウ" , speed:999 ,useweapon: "杖"},
	{id: 47 ,name: "フクロウ浄化型プリエステス" , group: "フクロウ" , speed:999 ,useweapon: "杖"},
	{id: 48 ,name: "フクロウ殲滅型ウィッチ" , group: "フクロウ" , speed:999 ,useweapon: "杖"},
	{id: 49 ,name: "フクロウ調律型スチームアームズ" , group: "フクロウ" , speed:999 ,useweapon: "杖"},
	{id: 50 ,name: "フクロウ劇場型プロトリサーチャー" , group: "フクロウ" , speed:999 ,useweapon: "杖"},
	{id: 51 ,name: "フクロウ真夏型スウィムドレス" , group: "フクロウ" , speed:999 ,useweapon: "杖"},
	{id: 52 ,name: "フクロウ対魔女ダストストーム" , group: "フクロウ" , speed:999 ,useweapon: "杖"},
	{id: 53 ,name: "フクロウ風月・対魔獣スタンダード" , group: "フクロウ" , speed:999 ,useweapon: "杖"},
	{id: 54 ,name: "フクロウ新春型コトブキハレギ" , group: "フクロウ" , speed:999 ,useweapon: "杖"},
	{id: 55 ,name: "フラミンゴ対魔獣スタンダード" , group: "フラミンゴ" , speed:999 ,useweapon: "杖"},
	{id: 56 ,name: "フラミンゴ仮想戦ライトフォーム" , group: "フラミンゴ" , speed:999 ,useweapon: "杖"},
	{id: 57 ,name: "フラミンゴ浄化型プリエステス" , group: "フラミンゴ" , speed:999 ,useweapon: "杖"},
	{id: 58 ,name: "フラミンゴ殲滅型ウィッチ" , group: "フラミンゴ" , speed:999 ,useweapon: "杖"},
	{id: 59 ,name: "フラミンゴ調律型スチームアームズ" , group: "フラミンゴ" , speed:999 ,useweapon: "杖"},
	{id: 60 ,name: "フラミンゴ劇場型プロトリサーチャー" , group: "フラミンゴ" , speed:999 ,useweapon: "杖"},
	{id: 61 ,name: "フラミンゴ真夏型スウィムドレス" , group: "フラミンゴ" , speed:999 ,useweapon: "杖"},
	{id: 62 ,name: "フラミンゴ花鳥・対魔獣スタンダード" , group: "フラミンゴ" , speed:999 ,useweapon: "杖"},
	{id: 63 ,name: "フラミンゴ暴虐型アークエンジェル" , group: "フラミンゴ" , speed:999 ,useweapon: "杖"},
	{id: 64 ,name: "フラミンゴ新春型コトブキハレギ" , group: "フラミンゴ" , speed:999 ,useweapon: "杖"},
	{id: 65 ,name: "ツル対魔獣スタンダード" , group: "ツル" , speed:999 ,useweapon: "杖"},
	{id: 66 ,name: "ツル仮想戦ライトフォーム" , group: "ツル" , speed:999 ,useweapon: "杖"},
	{id: 67 ,name: "ツル浄化型カンナギ" , group: "ツル" , speed:999 ,useweapon: "杖"},
	{id: 68 ,name: "ツル浄化型プリエステス" , group: "ツル" , speed:999 ,useweapon: "杖"},
	{id: 69 ,name: "ツル殲滅型アンデッド" , group: "ツル" , speed:999 ,useweapon: "杖"},
	{id: 70 ,name: "ツル天文型スターラヴァーズ" , group: "ツル" , speed:999 ,useweapon: "杖"},
	{id: 71 ,name: "ツル対魔女ダストストーム" , group: "ツル" , speed:999 ,useweapon: "杖"},
	{id: 72 ,name: "ツル納涼型ツキミユカタ" , group: "ツル" , speed:999 ,useweapon: "杖"},
	{id: 73 ,name: "ツル祭儀型トリックナイト" , group: "ツル" , speed:999 ,useweapon: "杖"},
	{id: 74 ,name: "ツル風月・対魔獣スタンダード" , group: "ツル" , speed:999 ,useweapon: "杖"},
	{id: 75 ,name: "ハチドリ対魔獣スタンダード" , group: "ハチドリ" , speed:999 ,useweapon: "杖"},
	{id: 76 ,name: "ハチドリ仮想戦ライトフォーム" , group: "ハチドリ" , speed:999 ,useweapon: "杖"},
	{id: 77 ,name: "ハチドリ浄化型カンナギ" , group: "ハチドリ" , speed:999 ,useweapon: "杖"},
	{id: 78 ,name: "ハチドリ浄化型プリエステス" , group: "ハチドリ" , speed:999 ,useweapon: "杖"},
	{id: 79 ,name: "ハチドリ殲滅型アンデッド" , group: "ハチドリ" , speed:999 ,useweapon: "杖"},
	{id: 80 ,name: "ハチドリ天文型スターラヴァーズ" , group: "ハチドリ" , speed:999 ,useweapon: "杖"},
	{id: 81 ,name: "ハチドリ対魔女ダストストーム" , group: "ハチドリ" , speed:999 ,useweapon: "杖"},
	{id: 82 ,name: "ハチドリ納涼型ツキミユカタ" , group: "ハチドリ" , speed:999 ,useweapon: "杖"},
	{id: 83 ,name: "ハチドリ祭儀型トリックナイト" , group: "ハチドリ" , speed:999 ,useweapon: "杖"},
	{id: 84 ,name: "ハチドリ花鳥・対魔獣スタンダード" , group: "ハチドリ" , speed:999 ,useweapon: "杖"},
	{id: 85 ,name: "ツバメ対魔獣スタンダード" , group: "ツバメ" , speed:999 ,useweapon: "杖"},
	{id: 86 ,name: "ツバメ仮想戦ライトフォーム" , group: "ツバメ" , speed:999 ,useweapon: "杖"},
	{id: 87 ,name: "ツバメ浄化型プリエステス" , group: "ツバメ" , speed:999 ,useweapon: "杖"},
	{id: 88 ,name: "ツバメ殲滅型ウィッチ" , group: "ツバメ" , speed:999 ,useweapon: "杖"},
	{id: 89 ,name: "ツバメ浄化型カンナギ" , group: "ツバメ" , speed:999 ,useweapon: "杖"},
	{id: 90 ,name: "ツバメ殲滅型アンデッド" , group: "ツバメ" , speed:999 ,useweapon: "杖"},
	{id: 91 ,name: "ツバメ納涼型ツキミユカタ" , group: "ツバメ" , speed:999 ,useweapon: "杖"},
	{id: 92 ,name: "ツバメ風月・対魔獣スタンダード" , group: "ツバメ" , speed:999 ,useweapon: "杖"},
	{id: 93 ,name: "ツバメ祭儀型セントホリデー" , group: "ツバメ" , speed:999 ,useweapon: "杖"},
	{id: 94 ,name: "ツバメ対魔女ダストストーム" , group: "ツバメ" , speed:999 ,useweapon: "杖"},
	{id: 95 ,name: "モズ対魔獣スタンダード" , group: "モズ" , speed:999 ,useweapon: "杖"},
	{id: 96 ,name: "モズ仮想戦ライトフォーム" , group: "モズ" , speed:999 ,useweapon: "杖"},
	{id: 97 ,name: "モズ浄化型プリエステス" , group: "モズ" , speed:999 ,useweapon: "杖"},
	{id: 98 ,name: "モズ殲滅型アンデッド" , group: "モズ" , speed:999 ,useweapon: "杖"},
	{id: 99 ,name: "モズ納涼型ツキミユカタ" , group: "モズ" , speed:999 ,useweapon: "杖"},
	{id: 100 ,name: "モズ風月・対魔獣スタンダード" , group: "モズ" , speed:999 ,useweapon: "杖"},
	{id: 101 ,name: "モズ祭儀型セントホリデー" , group: "モズ" , speed:999 ,useweapon: "杖"},
	{id: 102 ,name: "モズ対魔女ダストストーム" , group: "モズ" , speed:999 ,useweapon: "杖"},
	{id: 103 ,name: "カモメ対魔獣スタンダード" , group: "カモメ" , speed:999 ,useweapon: "杖"},
	{id: 104 ,name: "カモメ仮想戦ライトフォーム" , group: "カモメ" , speed:999 ,useweapon: "杖"},
	{id: 105 ,name: "アリス童話型スタンダード" , group: "コラボ" , speed:999 ,useweapon: "杖"},
	{id: 106 ,name: "アリス童話型イヴルレイヴン" , group: "コラボ" , speed:999 ,useweapon: "杖"},
	{id: 107 ,name: "アリス童話型オルタナティブ" , group: "コラボ" , speed:999 ,useweapon: "杖"},
	{id: 108 ,name: "スノウホワイト童話型スタンダード" , group: "コラボ" , speed:999 ,useweapon: "杖"},
	{id: 109 ,name: "スノウホワイト童話型イヴルスコーピオン" , group: "コラボ" , speed:999 ,useweapon: "杖"},
	{id: 110 ,name: "スノウホワイト童話型オルタナティブ" , group: "コラボ" , speed:999,useweapon: "杖"}

];